name: pixelpro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  firebase_storage: ^11.3.1
  firebase_database: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  material_symbols_icons: ^4.39.5
  image_picker: ^1.0.4
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.11.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/