name: pixelpro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  material_symbols_icons: ^4.39.5
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto